import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // Manual sidebar for Agentic AI book
  agenticSidebar: [
    {
      type: 'category',
      label: 'Agentic AI: A Comprehensive Guide',
      items: [
        'agentic-ai/intro',
        'agentic-ai/fundamentals',
        'agentic-ai/building-blocks',
        'agentic-ai/design-patterns',
        'agentic-ai/implementation',
        'agentic-ai/advanced-concepts',
        'agentic-ai/applications',
        'agentic-ai/evaluation',
        'agentic-ai/deployment',
        'agentic-ai/ethics',
        'agentic-ai/future',
        'agentic-ai/troubleshooting'
      ],
    },
  ],
};

export default sidebars;
